### ISSUE TITLE
array of globs for matcher

### ISSUE THREAD

**Issue by TrySound** [jonschlinkert/micromatch#48] opened 2015-11-14 21:53 UTC
Public api should also accept precompiled array of globs for matcher like filter. API parts should be similar, I think.

**Comment by jonschlinkert** [comment] 2015-11-14 22:02
> accept precompiled array of globs for matcher like filter.

agreed, this would be good to have. related https://github.com/jonschlinkert/micromatch/issues/35

> API parts should be similar, I think.

Meaning most or all methods should handle arrays of patterns? I'd have to think about that. There are many use cases for singular glob patterns, and when the function is optimized for a single pattern it's going to be faster.

**Comment by TrySound** [comment] 2015-11-14 22:18
Maybe need to make two versions of methods. Like filter<->filters, matcher<->matchers

**Comment by jonschlinkert** [comment] 2015-12-07 07:25
@TrySound is the expectation that **any** of the patterns can match, not **all**? if so I think this is a dupe of #35.

However, today I was doing something where I wanted to use an array of patterns and have **all** of them match (I was building up the array programmatically), so I just wanted to confirm. If it's the latter, we can just clarify the issue title

**Comment by TrySound** [comment] 2015-12-07 07:38
@jonschlinkert Yep. It's related.

**Comment by jonschlinkert** [comment] 2015-12-07 14:29
thanks, closing as a dupe

**Closed by jonschlinkert** 2015-12-07 14:29 UTC
Labels: request
