### ISSUE TITLE
globstar

### ISSUE THREAD

**Issue by MartinKolarik** [jonschlinkert/micromatch#59] opened 2016-04-01 00:19 UTC
AFAIK, the double star should only match multiple directories if it' the only thing in a path part, e.g., `a/**/b`, but not `a/b**`.

In micromatch, it seems it can be followed by other characters:

```js
mm.isMatch('a/b/c', 'a/b**'); // => returns false
mm.isMatch('a/c/b', 'a/**b'); // => returns true (maybe a bug?)
```

Is this intentional?

**Comment by jonschlinkert** [comment] 2016-04-01 23:45
> Is this intentional?

No, it's not. I'll look into it, thx

**Comment by tunnckoCore** [comment] 2016-04-22 09:49
> @MartinKolarik returns true (maybe a bug?)

I don't think so. It's not a bug for me.

> No, it's not.

@jonschlinkert @MartinKolarik, actually it is logical to be `true` because `*` means `0 or more`.

**Comment by MartinKolarik** [comment] 2016-04-22 09:56
@tunnckoCore it would make sense for `mm.isMatch('a/b', 'a/**b');`, but it shouldn't behave like globstar (matching multiple dirs) if it isn't the only thing in a path part.

**Comment by tunnckoCore** [comment] 2016-04-22 10:27
I'm not saying it should behave like globstar. I'm not sure for the my last sentence, just saying it make some sense.

And not, it not behaves as globstar, which is good and expected?

```js
console.log(mm.isMatch('a/b/c/d', 'a/**b')) // => false
```

**Comment by MartinKolarik** [comment] 2016-04-22 10:36
>console.log(mm.isMatch('a/b/c/d', 'a/**b')) // => false

It does if you fix the pattern: `console.log(mm.isMatch('a/b/c/d', 'a/**d')); // => true`

**Comment by jonschlinkert** [comment] 2016-04-22 21:24
The current behavior is correct. From the [bash specification](https://www.gnu.org/software/bash/manual/bashref.html#Pattern-Matching)

> two adjacent ‘*’s used as a single pattern will match all files and zero or more directories and subdirectories. If followed by a ‘/’, two adjacent ‘*’s will match only directories and subdirectories.

closing

**Comment by MartinKolarik** [comment] 2016-04-22 21:55
Well, the linked spec also doesn't say `mm.isMatch('a/b/c', 'a/b**');` shouldn't match, but it (I think correctly) doesn't. I wasn't able to find a spec covering this behavior, but it's documented in [minimatch's README](https://github.com/isaacs/minimatch#comparisons-to-other-fnmatchglob-implementations), and more importantly, it's how real bash works (just tested that).

**Comment by jonschlinkert** [comment] 2016-04-22 22:06
Hmm, okay. I remember implementing behavior based on my (literal) interpretation of the spec. But it seems this is a bit nuanced. 

fwiw I'm refactoring this to use a parser like the one implemented in the [refactor branch of extglob](https://github.com/jonschlinkert/extglob/tree/refactor). this will allow us to easily make changes based on discussions like this

**Comment by MartinKolarik** [comment] 2016-04-22 22:37
>fwiw I'm refactoring this to use a parser like the one implemented in the refactor branch of extglob. 

Looks good, that should definitely make it easier to handle situations like this.

**Comment by jonschlinkert** [comment] 2016-04-22 23:04
indeed, but the best part is that it's also much faster :)

**Comment by MartinKolarik** [comment] 2016-04-22 23:19
Really? It already is quite fast. Will definitely take a closer look at the code.

**Comment by jonschlinkert** [comment] 2016-04-23 02:22
more specifically it parses and compiles the regex patterns faster. so initialization will be faster, but not necessarily the actual matching. Hmm, I'm going to create an issue to get my thoughts out on this

**Comment by MartinKolarik** [comment] 2016-04-25 15:07
>more specifically it parses and compiles the regex patterns faster. so initialization will be faster, but not necessarily the actual matching

yeah that makes sense

**Closed** 2016-10-08 11:39 UTC
Labels: under review
