### ISSUE TITLE
Array with negation pattern

### ISSUE THREAD

**Issue by vweevers** [jonschlinkert/micromatch#9] opened 2015-02-22 09:55 UTC
As you noted in [level-glob#1](https://github.com/vweevers/level-glob/issues/1) (thanks!), there's a possible bug (I'm not sure either) when using multiple patterns and negation. I did some tests with both 1.0.1 and 1.4.2, and it comes down to the following. These two lines produce different results:

```js
var mm = require('micromatch');
console.log(mm.match(['a.md', 'b.js'], ['!*.md']));
console.log(mm.match(['a.md', 'b.js'], '!*.md'));
```

The first matches nothing, the second matches `b.js`. Is this expected behavior?

**Comment by jonschlinkert** [comment] 2015-02-27 00:49
sorry for the late reply! Ah, yes, not a bug, but... it was an implementation decision - but one I can easily change/revisit if necessary. 
The thinking is that:

- if you only pass a string pattern, then the behavior will be the same as minimatch. which is inclusive by default. Meaning `'!*.md'` should return everything except `'*.md'`. This is how minimatch works.
- however, if you pass an array of patterns (which isn't supported by minimatch), then the results should not be inclusive by default, so you have to do `['*', '!*.md']`. e.g. if you only want to negate `*.md`, then pass a string. 

We had similar discussions on multimatch, and it seems I might be in the minority in thinking that the current behavior makes sense, so I might change it with more feedback. Thoughts?

**Comment by vweevers** [comment] 2015-02-27 07:06
That explains it, thanks. Although this behavior is counter-intuitive to me (because I always read a negation pattern as "everything but x", and multiple negation pattterns as "everything but x and y"), it's sane to keep in line with multimatch. 

For now, what's missing, is a note in the readme. There's an example of multiple negation patterns:

```js
mm(['a.js', 'b.md', 'c.txt'], '!*.{js,txt}');
//=> ['b.md']

mm(['a.md', 'b.js', 'c.txt', 'd.json'], ['*.*', '!*.{js,txt}']);
//=> ['a.md', 'd.json']
```

.. which kind of reveals the behavior, but it's easy to miss. An explanation or at least an explicit comment would manage expectations and thus prevent confusion.

*For others, related discussion is here: sindresorhus/multimatch#7, sindresorhus/multimatch#10, robrich/gulp-match#4.*

**Comment by jonschlinkert** [comment] 2015-02-27 08:04
> what's missing, is a note in the readme

Good point. I'll get that inserted!

Thanks for the cross-references too!

**Comment by jonschlinkert** [comment] 2015-02-27 08:06
closing, I opened up an issue to add to docs. I'm not shutting down the idea of changing this behavior though. if you or anyone who has any thoughts on this wants to comment, please feel free

**Closed by jonschlinkert** 2015-02-27 08:06 UTC

**Comment by cben** [comment] 2023-05-01 11:43
> ... is counter-intuitive to me (because I always read a negation pattern as "everything but x", and multiple negation pattterns as "everything but x and y"), ...

I had the same intuition for multiple negations, but turns out it subtly depends on which API one uses.

For example I was naively assuming `micromatch.isMatch()` would be the boolean equivalent to `micromatch()` but turns out it's an alias for `any()` making it nearly useless with multiple negations:
```js
> micromatch.isMatch('/a/b/c.d', ['!/a/**'])
false
> micromatch.isMatch('/a/b/c.d', ['!/x/**'])
true
> micromatch.isMatch('/a/b/c.d', ['!/a/**', '!/x/**'])
true
```
WAT?  So the reason is that while "! a" rejects it, "! x" allows it and the result is true as long as at least one pattern allows it.  Only if ALL negations fail would `isMatch` = `any` fail:
```js
> micromatch.isMatch('/a/b/c.d', ['!/a/**'])
false
> micromatch.isMatch('/a/b/c.d', ['!/*/b/**'])
false
> micromatch.isMatch('/a/b/c.d', ['!/a/**', '!/*/b/**'])
false
```

----

The top-level micromatch() aka micromatch.match() is more intuitive:
```js
> micromatch(['/a/b/c.d', '/x/y', '/z'], ['!/a/**'])
[ '/x/y', '/z' ]
> micromatch(['/a/b/c.d', '/x/y', '/z'], ['!/x/**'])
[ '/a/b/c.d', '/z' ]
> micromatch(['/a/b/c.d', '/x/y', '/z'], ['!/a/**', '!/*/b/**'])
[ '/x/y', '/z' ]
> micromatch(['/a/b/c.d', '/x/y', '/z'], ['!/x/**', '!/a/**'])
[ '/z' ]
```
but the documentation is unclear how exactly it _should_ interpret multiple patterns.  
It merely states "patterns {String|Array}: One or more glob patterns to use for matching."

BTW, I don't see evidence that "you have to do `['*', '!*.md']`".  It seems that array with only negations does the job.

**Comment by magicdawn** [comment] 2023-10-25 18:20
+1 on weird behavior of current `mm.isMatch` when dealing with negation

> Returns true if any of the given glob patterns match the specified string.

Only run into issues can i  find out this api is not equal to `mm()`

**Comment by magicdawn** [comment] 2024-06-30 14:06
the `mm()` equivalent is a custom function to use `mm()` internally


to match *some* of postive patterns and *all* of negative patterns.


```ts
import mm from 'micromatch'

const str = '/a/b/c.d'
const patterns = ['*.d', '*.js', '!/a/**', '!/x/**']

console.log(mm.all(str, patterns)) // false
console.log(mm.isMatch(str, patterns)) // true
console.log(isMatch(str, patterns)) // false

console.log('---')
console.log(mm.all('index.js', patterns)) // false
console.log(mm.isMatch('index.js', patterns)) // true
console.log(isMatch('index.js', patterns)) // true

export function isMatch(str: string, patterns: string | string[]) {
  return !!mm([str], patterns).length
}
```
